spring:
  application:
    name: eureka server
server:
  port: 8761
eureka:
  server:
    peer-node-read-timeout-ms: ${PEER_NODE_READ_TIMEOUT_MS:1000}
    enable-self-preservation: ${ENABLE_SELF_PRESERVATION:false}
    eviction-interval-timer-in-ms: ${EVICTION_INTERVAL_TIMER_IN_MS:60000}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URLS:http://admin:123456@localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: [ 'health','info' ]