{{- if ne .Values.namespace "default" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
{{- end }}
---
{{- if .Values.customConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.customConfig.name | default "eureka-application-config" }}
{{- if ne .Values.namespace "default" }}
  namespace: {{ .Values.namespace }}
{{- end }}
data:
{{- toYaml .Values.customConfig.data | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
{{- if ne .Values.namespace "default" }}
  namespace: {{ .Values.namespace }}
{{- end }}
data:
  {{- toYaml .Values.env | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessServiceName | default "eureka-headless" }}
{{- if ne .Values.namespace "default" }}
  namespace: {{ .Values.namespace }}
{{- end }}
spec:
  clusterIP: None
  selector:
{{- toYaml .Values.labels | nindent 4 }}
  ports:
  - name: http
    port: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default "eureka" }}
{{- if ne .Values.namespace "default" }}
  namespace: {{ .Values.namespace }}
{{- end }}
spec:
{{- if .Values.service.type }}
  type: {{ .Values.service.type }}
{{- end }} 
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
  ports:
  - name: http
    port: 8761
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort | default 30876 }}
{{- end }}
  selector:
{{- toYaml .Values.labels | nindent 4 }}
---
apiVersion: {{ .Values.statefulSetApiVersion | default "apps/v1" }}
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSetName | default "eureka" }}
{{- if ne .Values.namespace "default" }}
  namespace: {{ .Values.namespace }}
{{- end }}
spec:
  replicas: {{ .Values.replicas | default 3 }}
  serviceName: {{ .Values.headlessServiceName | default "eureka-headless" }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
{{- if .Values.customConfig }}
      volumes:
      - name: {{ .Values.customConfig.name | default "eureka-application-config" }}
        configMap:
          name: {{ .Values.customConfig.name | default "eureka-application-config" }}
          items:
          - key: application.yml
            path: application.yml
      {{- if .Values.customVolume }}
      - name: {{ .Values.customVolume.name | default "eureka-custom-volume" }}
        {{- toYaml .Values.customVolume.volume | nindent 8 }}
      {{- end }}
{{- else }}
{{- if .Values.customVolume }}
      volumes:
      - name: {{ .Values.customVolume.name | default "eureka-custom-volume" }}
        {{- toYaml .Values.customVolume.volume | nindent 8 }}
{{- end }}
{{- end }}
      containers:
      - name: eureka
        image: {{ .Values.image | default "lhstack/eureka" }}:{{ .Values.version | default "latest" }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8761
        envFrom:
        - configMapRef:
            name: {{ .Values.configMapName }}
{{- if .Values.customConfig }}
        volumeMounts:
        - name: {{ .Values.customConfig.name | default "eureka-application-config" }}
          mountPath: /eureka/conf/application.yml
          subPath: application.yml
{{- if .Values.customVolume }}
        - name: {{ .Values.customVolume.name | default "eureka-custom-volume" }}
          {{- toYaml .Values.customVolume.volumeMount | nindent 10 }}
{{- end }}
{{- else }}
{{- if .Values.customVolume }}
        volumeMounts:
        - name: {{ .Values.customVolume.name | default "eureka-custom-volume" }}
          {{- toYaml .Values.customVolume.volumeMount | nindent 10 }}
{{- end }}
{{- end }}
        env:
        - name: IS_STATEFUL_SET
          value: "true"
        - name: NAMESPACE
          value: {{ .Values.namespace | default "default" | quote }}
        - name: SERVICE_NAME
          value: {{ .Values.headlessServiceName | default "eureka-headless" | quote }}
        - name: REPLICAS
          value: {{ .Values.replicas | default 3 | quote }}
{{- if .Values.resources }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
{{- if .Values.env.ENABLE_SSL }}
            scheme: HTTPS
{{- end }}
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
{{- if .Values.env.ENABLE_SSL }}
            scheme: HTTPS
{{- end }}
          initialDelaySeconds: 60
          failureThreshold: 5
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 2
