apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-admin
data:
  EUREKA_SERVER_URL: "http://admin:123456@10.43.87.61:8761/eureka"
  SECURITY_USERNAME: "admin"
  SECURITY_PASSWORD: "123456"
  JAVA_OPTS: "-Xmx512m -Xms512m"
---
apiVersion: v1
kind: Service
metadata:
  name: boot-admin
spec:
  selector:
    app: boot-admin
    register-service: eureka
  ports:
  - port: 8800
  type: ClusterIP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: boot-admin
spec:
  replicas: 1
  selector:
    app: boot-admin
    register-service: eureka
  template:
    metadata:
      labels:
        app: boot-admin
        register-service: eureka
    spec:
      containers:
      - name: boot-admin
        image: boot-admin:11-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8800
        envFrom:
        - configMapRef:
            name: boot-admin
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8800
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8800
          initialDelaySeconds: 60
          failureThreshold: 5
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 2