apiVersion: v1
kind: Namespace
metadata:
  name: eureka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka
  namespace: eureka
data:
  SECURITY_USERNAME: "admin"
  SECURITY_PASSWORD: "123456"
  EUREKA_SERVER_URLS: "http://admin:123456@eureka-headless.eureka.svc.cluster.local:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-headless
  namespace: eureka
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: eureka-replica
  ports:
  - name: http
    port: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: eureka
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8761
  selector:
    app: eureka
  clusterIP: 10.43.87.61
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-cluster
  namespace: eureka
spec:
  replicas: 2
  serviceName: eureka-headless
  selector:
    matchLabels:
      app: eureka-replica
  template:
    metadata:
      labels:
        app: eureka-replica
    spec:
      containers:
      - name: eureka
        image: eureka:11-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8761
        env:
        - name: IS_STATEFUL_SET
          value: "true"
        - name: NAMESPACE
          value: "eureka"
        - name: SECURITY_ENABLE
          value: "true"
        - name: SECURITY_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SECURITY_USERNAME
              name: eureka
        - name: SECURITY_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SECURITY_PASSWORD
              name: eureka
        - name: SERVICE_NAME
          value: "eureka-headless"
        - name: REPLICAS
          value: "2"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms512m"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          failureThreshold: 5
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deploy
  namespace: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: eureka:11-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8761
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          failureThreshold: 5
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 512Mi
        env:
        - name: SECURITY_ENABLE
          value: "true"
        - name: SECURITY_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SECURITY_USERNAME
              name: eureka
        - name: SECURITY_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SECURITY_PASSWORD
              name: eureka
        - name: EUREKA_SERVER_URLS
          valueFrom:
            configMapKeyRef:
              key: EUREKA_SERVER_URLS
              name: eureka
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms512m -Deureka.client.fetch-registry=true -Deureka.client.register-with-eureka=true"